### ISSUE TITLE
Cannot upload file for email sending

### ISSUE THREAD

**Issue by gilbertotcc** [iamleot/transferwee#2]
I'm trying to upload a file with a sender address and a recipient address, but the script doesn't work as expected.

```shell
gilberto@margot:~/$ ./transferwee/transferwee.py upload -m "New CV created" -f <sender_email> -t <recipient_email> FILE 
usage: transferwee upload [-h] [-m message] [-f from] [-t to [to ...]]
                          file [file ...]
transferwee upload: error: the following arguments are required: file
```
Am I wrong in calling the script?

**Comment by iamleot** [comment]
Hello Gilberto!

Gilberto Taccari writes:
> I'm trying to upload a file with a sender address and a recipient address, but the script doesn't work as expected.
>
> ```shell
> gilberto@margot:~/$ ./transferwee/transferwee.py upload -m "New CV created" -f <sender_email> -t <recipient_email> FILE 
> usage: transferwee upload [-h] [-m message] [-f from] [-t to [to ...]]
>                           file [file ...]
> transferwee upload: error: the following arguments are required: file
> ```
> Am I wrong in calling the script?

Because the `-t' option supports multiple addresses a `--' is needed
to separate it with the file.
Can you please try the following:

 $ ./transferwee/transferwee.py upload -m "New CV created" -f <sender_email> -t <recipient_email> -- FILE 

and let me know if that works?


Thank you!


(The README contains a note about that but yeah, that's a bit
confusing!)

**Comment by gilbertotcc** [comment]
You're right. Thanks for the suggestion. It wasn't an issue on code.
